### ISSUE TITLE
Support for stacked bar chart

### ISSUE THREAD

**Issue by vladanyes** [vladanyes/react-native-skia-charts#2]
add stacked bar chart implementation where the data/datasets prop should be similar to this:
```const datasetsDefault = [
  {
    label: 'First item',
    color: 'red',
    data: [
      {
        date: '2020-01-01',
        value: 10,
      },
      ...
    ],
  },
  {
    label: 'Second item',
    color: 'green',
    data: [
      {
        date: '2020-01-02',
        value: 20,
      },
      ...
    ],
  },
  ...
];
```

**Comment by vladanyes** [comment]
hey @adityakmr7 , thank you for the interest in this library! The thing is, I implemented stacked bar chart using react-native-skia a couple months ago. Now I need to do some cleanups and improvements prior to adding it to this repo.

**Comment by adityakmr7** [comment]
Cool, I also wanted to create a library for chart using react-native-skia. I would love to contribute to this project of yours. Let me know if you need any help. And I will also try to add some of the graph type in this repo.
